/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.predsparser.analysis;

import soot.jimple.toolkits.ctl.predsparser.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAFile(AFile node);
    void caseAFormalsPred(AFormalsPred node);
    void caseAGroundPred(AGroundPred node);
    void caseAFormal(AFormal node);
    void caseASingleFormalList(ASingleFormalList node);
    void caseAMultiFormalList(AMultiFormalList node);

    void caseTLParen(TLParen node);
    void caseTRParen(TRParen node);
    void caseTArr(TArr node);
    void caseTComma(TComma node);
    void caseTMetaType(TMetaType node);
    void caseTIdentifier(TIdentifier node);
    void caseTIgnored(TIgnored node);
    void caseTAny(TAny node);
    void caseEOF(EOF node);
}
