/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.predsparser.parser;

import soot.jimple.toolkits.ctl.predsparser.node.*;
import soot.jimple.toolkits.ctl.predsparser.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTLParen(@SuppressWarnings("unused") TLParen node)
    {
        this.index = 0;
    }

    @Override
    public void caseTRParen(@SuppressWarnings("unused") TRParen node)
    {
        this.index = 1;
    }

    @Override
    public void caseTArr(@SuppressWarnings("unused") TArr node)
    {
        this.index = 2;
    }

    @Override
    public void caseTComma(@SuppressWarnings("unused") TComma node)
    {
        this.index = 3;
    }

    @Override
    public void caseTMetaType(@SuppressWarnings("unused") TMetaType node)
    {
        this.index = 4;
    }

    @Override
    public void caseTIdentifier(@SuppressWarnings("unused") TIdentifier node)
    {
        this.index = 5;
    }

    @Override
    public void caseTAny(@SuppressWarnings("unused") TAny node)
    {
        this.index = 6;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 7;
    }
}
