/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.predsparser.node;

import soot.jimple.toolkits.ctl.predsparser.analysis.*;

@SuppressWarnings("nls")
public final class AFormal extends PFormal
{
    private TMetaType _metaType_;
    private TIdentifier _identifier_;

    public AFormal()
    {
        // Constructor
    }

    public AFormal(
        @SuppressWarnings("hiding") TMetaType _metaType_,
        @SuppressWarnings("hiding") TIdentifier _identifier_)
    {
        // Constructor
        setMetaType(_metaType_);

        setIdentifier(_identifier_);

    }

    @Override
    public Object clone()
    {
        return new AFormal(
            cloneNode(this._metaType_),
            cloneNode(this._identifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFormal(this);
    }

    public TMetaType getMetaType()
    {
        return this._metaType_;
    }

    public void setMetaType(TMetaType node)
    {
        if(this._metaType_ != null)
        {
            this._metaType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._metaType_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._metaType_)
            + toString(this._identifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._metaType_ == child)
        {
            this._metaType_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._metaType_ == oldChild)
        {
            setMetaType((TMetaType) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
