/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.predsparser.node;

import soot.jimple.toolkits.ctl.predsparser.analysis.*;

@SuppressWarnings("nls")
public final class TArr extends Token
{
    public TArr()
    {
        super.setText("#");
    }

    public TArr(int line, int pos)
    {
        super.setText("#");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TArr(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTArr(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TArr text.");
    }
}
