/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.predsparser.node;

import soot.jimple.toolkits.ctl.predsparser.analysis.*;

@SuppressWarnings("nls")
public final class TIgnored extends Token
{
    public TIgnored(String text)
    {
        setText(text);
    }

    public TIgnored(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIgnored(getText(), getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIgnored(this);
    }
}
