/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AAwFormula extends PFormula
{
    private TAlways _always_;
    private TLParen _lParen_;
    private PFormula _l_;
    private TWuntil _wuntil_;
    private PFormula _r_;
    private TRParen _rParen_;

    public AAwFormula()
    {
        // Constructor
    }

    public AAwFormula(
        @SuppressWarnings("hiding") TAlways _always_,
        @SuppressWarnings("hiding") TLParen _lParen_,
        @SuppressWarnings("hiding") PFormula _l_,
        @SuppressWarnings("hiding") TWuntil _wuntil_,
        @SuppressWarnings("hiding") PFormula _r_,
        @SuppressWarnings("hiding") TRParen _rParen_)
    {
        // Constructor
        setAlways(_always_);

        setLParen(_lParen_);

        setL(_l_);

        setWuntil(_wuntil_);

        setR(_r_);

        setRParen(_rParen_);

    }

    @Override
    public Object clone()
    {
        return new AAwFormula(
            cloneNode(this._always_),
            cloneNode(this._lParen_),
            cloneNode(this._l_),
            cloneNode(this._wuntil_),
            cloneNode(this._r_),
            cloneNode(this._rParen_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAwFormula(this);
    }

    public TAlways getAlways()
    {
        return this._always_;
    }

    public void setAlways(TAlways node)
    {
        if(this._always_ != null)
        {
            this._always_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._always_ = node;
    }

    public TLParen getLParen()
    {
        return this._lParen_;
    }

    public void setLParen(TLParen node)
    {
        if(this._lParen_ != null)
        {
            this._lParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lParen_ = node;
    }

    public PFormula getL()
    {
        return this._l_;
    }

    public void setL(PFormula node)
    {
        if(this._l_ != null)
        {
            this._l_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._l_ = node;
    }

    public TWuntil getWuntil()
    {
        return this._wuntil_;
    }

    public void setWuntil(TWuntil node)
    {
        if(this._wuntil_ != null)
        {
            this._wuntil_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._wuntil_ = node;
    }

    public PFormula getR()
    {
        return this._r_;
    }

    public void setR(PFormula node)
    {
        if(this._r_ != null)
        {
            this._r_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._r_ = node;
    }

    public TRParen getRParen()
    {
        return this._rParen_;
    }

    public void setRParen(TRParen node)
    {
        if(this._rParen_ != null)
        {
            this._rParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rParen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._always_)
            + toString(this._lParen_)
            + toString(this._l_)
            + toString(this._wuntil_)
            + toString(this._r_)
            + toString(this._rParen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._always_ == child)
        {
            this._always_ = null;
            return;
        }

        if(this._lParen_ == child)
        {
            this._lParen_ = null;
            return;
        }

        if(this._l_ == child)
        {
            this._l_ = null;
            return;
        }

        if(this._wuntil_ == child)
        {
            this._wuntil_ = null;
            return;
        }

        if(this._r_ == child)
        {
            this._r_ = null;
            return;
        }

        if(this._rParen_ == child)
        {
            this._rParen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._always_ == oldChild)
        {
            setAlways((TAlways) newChild);
            return;
        }

        if(this._lParen_ == oldChild)
        {
            setLParen((TLParen) newChild);
            return;
        }

        if(this._l_ == oldChild)
        {
            setL((PFormula) newChild);
            return;
        }

        if(this._wuntil_ == oldChild)
        {
            setWuntil((TWuntil) newChild);
            return;
        }

        if(this._r_ == oldChild)
        {
            setR((PFormula) newChild);
            return;
        }

        if(this._rParen_ == oldChild)
        {
            setRParen((TRParen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
