/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AAxFormula extends PFormula
{
    private TAlwaysNext _alwaysNext_;
    private PFormula _formula_;

    public AAxFormula()
    {
        // Constructor
    }

    public AAxFormula(
        @SuppressWarnings("hiding") TAlwaysNext _alwaysNext_,
        @SuppressWarnings("hiding") PFormula _formula_)
    {
        // Constructor
        setAlwaysNext(_alwaysNext_);

        setFormula(_formula_);

    }

    @Override
    public Object clone()
    {
        return new AAxFormula(
            cloneNode(this._alwaysNext_),
            cloneNode(this._formula_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAxFormula(this);
    }

    public TAlwaysNext getAlwaysNext()
    {
        return this._alwaysNext_;
    }

    public void setAlwaysNext(TAlwaysNext node)
    {
        if(this._alwaysNext_ != null)
        {
            this._alwaysNext_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._alwaysNext_ = node;
    }

    public PFormula getFormula()
    {
        return this._formula_;
    }

    public void setFormula(PFormula node)
    {
        if(this._formula_ != null)
        {
            this._formula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._alwaysNext_)
            + toString(this._formula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._alwaysNext_ == child)
        {
            this._alwaysNext_ = null;
            return;
        }

        if(this._formula_ == child)
        {
            this._formula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._alwaysNext_ == oldChild)
        {
            setAlwaysNext((TAlwaysNext) newChild);
            return;
        }

        if(this._formula_ == oldChild)
        {
            setFormula((PFormula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
