/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AEuFormula extends PFormula
{
    private TExists _exists_;
    private TLParen _lParen_;
    private PFormula _l_;
    private TUntil _until_;
    private PFormula _r_;
    private TRParen _rParen_;

    public AEuFormula()
    {
        // Constructor
    }

    public AEuFormula(
        @SuppressWarnings("hiding") TExists _exists_,
        @SuppressWarnings("hiding") TLParen _lParen_,
        @SuppressWarnings("hiding") PFormula _l_,
        @SuppressWarnings("hiding") TUntil _until_,
        @SuppressWarnings("hiding") PFormula _r_,
        @SuppressWarnings("hiding") TRParen _rParen_)
    {
        // Constructor
        setExists(_exists_);

        setLParen(_lParen_);

        setL(_l_);

        setUntil(_until_);

        setR(_r_);

        setRParen(_rParen_);

    }

    @Override
    public Object clone()
    {
        return new AEuFormula(
            cloneNode(this._exists_),
            cloneNode(this._lParen_),
            cloneNode(this._l_),
            cloneNode(this._until_),
            cloneNode(this._r_),
            cloneNode(this._rParen_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEuFormula(this);
    }

    public TExists getExists()
    {
        return this._exists_;
    }

    public void setExists(TExists node)
    {
        if(this._exists_ != null)
        {
            this._exists_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exists_ = node;
    }

    public TLParen getLParen()
    {
        return this._lParen_;
    }

    public void setLParen(TLParen node)
    {
        if(this._lParen_ != null)
        {
            this._lParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._lParen_ = node;
    }

    public PFormula getL()
    {
        return this._l_;
    }

    public void setL(PFormula node)
    {
        if(this._l_ != null)
        {
            this._l_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._l_ = node;
    }

    public TUntil getUntil()
    {
        return this._until_;
    }

    public void setUntil(TUntil node)
    {
        if(this._until_ != null)
        {
            this._until_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._until_ = node;
    }

    public PFormula getR()
    {
        return this._r_;
    }

    public void setR(PFormula node)
    {
        if(this._r_ != null)
        {
            this._r_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._r_ = node;
    }

    public TRParen getRParen()
    {
        return this._rParen_;
    }

    public void setRParen(TRParen node)
    {
        if(this._rParen_ != null)
        {
            this._rParen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._rParen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exists_)
            + toString(this._lParen_)
            + toString(this._l_)
            + toString(this._until_)
            + toString(this._r_)
            + toString(this._rParen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exists_ == child)
        {
            this._exists_ = null;
            return;
        }

        if(this._lParen_ == child)
        {
            this._lParen_ = null;
            return;
        }

        if(this._l_ == child)
        {
            this._l_ = null;
            return;
        }

        if(this._until_ == child)
        {
            this._until_ = null;
            return;
        }

        if(this._r_ == child)
        {
            this._r_ = null;
            return;
        }

        if(this._rParen_ == child)
        {
            this._rParen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exists_ == oldChild)
        {
            setExists((TExists) newChild);
            return;
        }

        if(this._lParen_ == oldChild)
        {
            setLParen((TLParen) newChild);
            return;
        }

        if(this._l_ == oldChild)
        {
            setL((PFormula) newChild);
            return;
        }

        if(this._until_ == oldChild)
        {
            setUntil((TUntil) newChild);
            return;
        }

        if(this._r_ == oldChild)
        {
            setR((PFormula) newChild);
            return;
        }

        if(this._rParen_ == oldChild)
        {
            setRParen((TRParen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
