/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AExFormula extends PFormula
{
    private TExistsNext _existsNext_;
    private PFormula _formula_;

    public AExFormula()
    {
        // Constructor
    }

    public AExFormula(
        @SuppressWarnings("hiding") TExistsNext _existsNext_,
        @SuppressWarnings("hiding") PFormula _formula_)
    {
        // Constructor
        setExistsNext(_existsNext_);

        setFormula(_formula_);

    }

    @Override
    public Object clone()
    {
        return new AExFormula(
            cloneNode(this._existsNext_),
            cloneNode(this._formula_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExFormula(this);
    }

    public TExistsNext getExistsNext()
    {
        return this._existsNext_;
    }

    public void setExistsNext(TExistsNext node)
    {
        if(this._existsNext_ != null)
        {
            this._existsNext_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._existsNext_ = node;
    }

    public PFormula getFormula()
    {
        return this._formula_;
    }

    public void setFormula(PFormula node)
    {
        if(this._formula_ != null)
        {
            this._formula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._existsNext_)
            + toString(this._formula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._existsNext_ == child)
        {
            this._existsNext_ = null;
            return;
        }

        if(this._formula_ == child)
        {
            this._formula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._existsNext_ == oldChild)
        {
            setExistsNext((TExistsNext) newChild);
            return;
        }

        if(this._formula_ == oldChild)
        {
            setFormula((PFormula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
