/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class AFormal extends PFormal
{
    private PJimpleType _jimpleType_;
    private TIdentifier _identifier_;

    public AFormal()
    {
        // Constructor
    }

    public AFormal(
        @SuppressWarnings("hiding") PJimpleType _jimpleType_,
        @SuppressWarnings("hiding") TIdentifier _identifier_)
    {
        // Constructor
        setJimpleType(_jimpleType_);

        setIdentifier(_identifier_);

    }

    @Override
    public Object clone()
    {
        return new AFormal(
            cloneNode(this._jimpleType_),
            cloneNode(this._identifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFormal(this);
    }

    public PJimpleType getJimpleType()
    {
        return this._jimpleType_;
    }

    public void setJimpleType(PJimpleType node)
    {
        if(this._jimpleType_ != null)
        {
            this._jimpleType_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._jimpleType_ = node;
    }

    public TIdentifier getIdentifier()
    {
        return this._identifier_;
    }

    public void setIdentifier(TIdentifier node)
    {
        if(this._identifier_ != null)
        {
            this._identifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._jimpleType_)
            + toString(this._identifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._jimpleType_ == child)
        {
            this._jimpleType_ = null;
            return;
        }

        if(this._identifier_ == child)
        {
            this._identifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._jimpleType_ == oldChild)
        {
            setJimpleType((PJimpleType) newChild);
            return;
        }

        if(this._identifier_ == oldChild)
        {
            setIdentifier((TIdentifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
