/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ANotFormula extends PFormula
{
    private TNot _not_;
    private PFormula _formula_;

    public ANotFormula()
    {
        // Constructor
    }

    public ANotFormula(
        @SuppressWarnings("hiding") TNot _not_,
        @SuppressWarnings("hiding") PFormula _formula_)
    {
        // Constructor
        setNot(_not_);

        setFormula(_formula_);

    }

    @Override
    public Object clone()
    {
        return new ANotFormula(
            cloneNode(this._not_),
            cloneNode(this._formula_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANotFormula(this);
    }

    public TNot getNot()
    {
        return this._not_;
    }

    public void setNot(TNot node)
    {
        if(this._not_ != null)
        {
            this._not_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._not_ = node;
    }

    public PFormula getFormula()
    {
        return this._formula_;
    }

    public void setFormula(PFormula node)
    {
        if(this._formula_ != null)
        {
            this._formula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._formula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._not_)
            + toString(this._formula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._not_ == child)
        {
            this._not_ = null;
            return;
        }

        if(this._formula_ == child)
        {
            this._formula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._not_ == oldChild)
        {
            setNot((TNot) newChild);
            return;
        }

        if(this._formula_ == oldChild)
        {
            setFormula((PFormula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
