/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ANothingStatement extends PStatement
{
    private TNothing _nothing_;
    private TSemicolon _semicolon_;

    public ANothingStatement()
    {
        // Constructor
    }

    public ANothingStatement(
        @SuppressWarnings("hiding") TNothing _nothing_,
        @SuppressWarnings("hiding") TSemicolon _semicolon_)
    {
        // Constructor
        setNothing(_nothing_);

        setSemicolon(_semicolon_);

    }

    @Override
    public Object clone()
    {
        return new ANothingStatement(
            cloneNode(this._nothing_),
            cloneNode(this._semicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANothingStatement(this);
    }

    public TNothing getNothing()
    {
        return this._nothing_;
    }

    public void setNothing(TNothing node)
    {
        if(this._nothing_ != null)
        {
            this._nothing_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nothing_ = node;
    }

    public TSemicolon getSemicolon()
    {
        return this._semicolon_;
    }

    public void setSemicolon(TSemicolon node)
    {
        if(this._semicolon_ != null)
        {
            this._semicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._semicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nothing_)
            + toString(this._semicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nothing_ == child)
        {
            this._nothing_ = null;
            return;
        }

        if(this._semicolon_ == child)
        {
            this._semicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nothing_ == oldChild)
        {
            setNothing((TNothing) newChild);
            return;
        }

        if(this._semicolon_ == oldChild)
        {
            setSemicolon((TSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
