/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import java.util.*;
import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class ARedBody extends PRedBody
{
    private final LinkedList<PPredicate> _predicate_ = new LinkedList<PPredicate>();
    private final LinkedList<PCondition> _condition_ = new LinkedList<PCondition>();
    private final LinkedList<PRewrite> _rewrite_ = new LinkedList<PRewrite>();

    public ARedBody()
    {
        // Constructor
    }

    public ARedBody(
        @SuppressWarnings("hiding") List<PPredicate> _predicate_,
        @SuppressWarnings("hiding") List<PCondition> _condition_,
        @SuppressWarnings("hiding") List<PRewrite> _rewrite_)
    {
        // Constructor
        setPredicate(_predicate_);

        setCondition(_condition_);

        setRewrite(_rewrite_);

    }

    @Override
    public Object clone()
    {
        return new ARedBody(
            cloneList(this._predicate_),
            cloneList(this._condition_),
            cloneList(this._rewrite_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARedBody(this);
    }

    public LinkedList<PPredicate> getPredicate()
    {
        return this._predicate_;
    }

    public void setPredicate(List<PPredicate> list)
    {
        this._predicate_.clear();
        this._predicate_.addAll(list);
        for(PPredicate e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public LinkedList<PCondition> getCondition()
    {
        return this._condition_;
    }

    public void setCondition(List<PCondition> list)
    {
        this._condition_.clear();
        this._condition_.addAll(list);
        for(PCondition e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public LinkedList<PRewrite> getRewrite()
    {
        return this._rewrite_;
    }

    public void setRewrite(List<PRewrite> list)
    {
        this._rewrite_.clear();
        this._rewrite_.addAll(list);
        for(PRewrite e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._predicate_)
            + toString(this._condition_)
            + toString(this._rewrite_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._predicate_.remove(child))
        {
            return;
        }

        if(this._condition_.remove(child))
        {
            return;
        }

        if(this._rewrite_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PPredicate> i = this._predicate_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PPredicate) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PCondition> i = this._condition_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PCondition) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PRewrite> i = this._rewrite_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PRewrite) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
