/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class TAlways extends Token
{
    public TAlways()
    {
        super.setText("A");
    }

    public TAlways(int line, int pos)
    {
        super.setText("A");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAlways(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAlways(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAlways text.");
    }
}
