/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class TAlwaysNext extends Token
{
    public TAlwaysNext()
    {
        super.setText("AX");
    }

    public TAlwaysNext(int line, int pos)
    {
        super.setText("AX");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TAlwaysNext(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTAlwaysNext(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TAlwaysNext text.");
    }
}
