/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class TExistsNext extends Token
{
    public TExistsNext()
    {
        super.setText("EX");
    }

    public TExistsNext(int line, int pos)
    {
        super.setText("EX");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TExistsNext(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTExistsNext(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TExistsNext text.");
    }
}
