/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class TNext extends Token
{
    public TNext()
    {
        super.setText("X");
    }

    public TNext(int line, int pos)
    {
        super.setText("X");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TNext(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTNext(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TNext text.");
    }
}
