/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class TOror extends Token
{
    public TOror()
    {
        super.setText("||");
    }

    public TOror(int line, int pos)
    {
        super.setText("||");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TOror(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTOror(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TOror text.");
    }
}
