/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class TPred extends Token
{
    public TPred()
    {
        super.setText("pred");
    }

    public TPred(int line, int pos)
    {
        super.setText("pred");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TPred(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTPred(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TPred text.");
    }
}
