/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class TRed extends Token
{
    public TRed()
    {
        super.setText("transformation");
    }

    public TRed(int line, int pos)
    {
        super.setText("transformation");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TRed(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTRed(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TRed text.");
    }
}
