/* This file was generated by SableCC (http://www.sablecc.org/). */

package soot.jimple.toolkits.ctl.parser.node;

import soot.jimple.toolkits.ctl.parser.analysis.*;

@SuppressWarnings("nls")
public final class TTransform extends Token
{
    public TTransform()
    {
        super.setText("transform");
    }

    public TTransform(int line, int pos)
    {
        super.setText("transform");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTransform(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTransform(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTransform text.");
    }
}
